export enum ComponentType {
    VALARM = 'VALARM',
    VAVAILABILITY = 'VAVAILABILITY',
    VAVAILABLE = 'AVAILABLE',
    VEVENT = 'VEVENT',
    VFREEBUSY = 'VFREEBUSY',
    VJOURNAL = 'VJOURNAL',
    VTIMEZONE = 'VTIMEZONE',
    VTODO = 'VTODO',
    VVENUE = 'VVENUE'
}
